---
title: "Descriptive Stats"
output: html_document
---


```{r}
library(tidyverse)
# install.packages("prophet")
library(prophet)
library(lubridate)
library(here)
library(httpgd)
```
```{r}
hgd()
hgd_browse()
```

Create one DF:
```{r}
cherry <- read.csv(here("data",  "washingtondc.csv")) %>% 
  bind_rows(read.csv(here("data",  "liestal.csv"))) %>% 
  bind_rows(read.csv(here("data",  "kyoto.csv")))

```

First Peak into data:
```{r}
cherry %>% 
  group_by(location) %>% 
  slice_tail(n = 3)


cherry  %>%  
    split(.$location)  %>% 
    map(summary)

cherry %>% 
  filter(year >= 1880) %>%
  ggplot(aes(x = year, y = bloom_doy)) +
  geom_point() +
  geom_step(linetype = 'dotted', color = 'gray50') +
  scale_x_continuous(breaks = seq(1880, 2020, by = 20)) +
  facet_grid(cols = vars(str_to_title(location))) +
  labs(x = "Year", y = "Peak bloom (days since Jan 1st)")
```

## Test Prophet

```{r}

## Prophet model
tokyo_pred  <- cherry  %>% 
    # filter(location == "kyoto")  %>% 
    select(bloom_doy, bloom_date)  %>% 
    rename(y = bloom_doy, ds = bloom_date)  %>% 
    prophet()

## Create DF with future dates for later predictions
future <- make_future_dataframe(tokyo_pred, periods = 10, freq = "year")  %>% 
    filter(year(ds) >= 1880 & year(ds) <= 2031)  %>% 
    mutate(year = year(ds))

forecast  <- predict(tokyo_pred, future)

tokyo_pred  %>% str()

forecast  %>% str()

forecast  %>% select(ds, trend, yhat)

## Plot Predictions
plot(tokyo_pred, forecast) + add_changepoints_to_plot(tokyo_pred)

## interactive plot
dyplot.prophet(tokyo_pred, forecast)

# Compontent Plot
prophet_plot_components(tokyo_pred, forecast)
```
# To-dos
# - Bräuchte eine Funktion die mir vorhergesagtes und reales in bestimmten Zeitabstand plottet. Am besten mit facet-grid für alle Länder untersch.
# 
